{
 "title": "Евгений Ермак / Evgenii Ermak",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Процессор",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU, %"
    }
   ]
  },
  {
   "title": "Память",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "RAM used, %"
    }
   ]
  },
  {
   "title": "Диск",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"nvme0n1\"}[1m])",
     "legendFormat": "Чтение"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"nvme0n1\"}[1m])",
     "legendFormat": "Запись"
    }
   ]
  },
  {
   "title": "Сеть",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp2s0\"}[1m]) * 8",
     "legendFormat": "Входящий"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp2s0\"}[1m]) * 8",
     "legendFormat": "Исходящий"
    }
   ]
  }
 ]
}